get back e2e/spectron tests running on CI envs
* "saveScreenshot" function disabled for now since internal spectron's "browserWindow.capturePage" call ends up with the following error (stable "spectron" release is not yet available for @electron v10):
  Unhandled Promise Rejection
  Error: Failed to serialize arguments
      at WebContents../lib/browser/api/web-contents.js.WebContents._sendToFrameInternal (electron/js2c/browser_init.js:3645:15)
      at callIntoRenderer (electron/js2c/browser_init.js:6173:42)